version: '3.3'
actions:
- action: "Build dockerfile"
  type: "txt"
  region: "us-east-1"
  integration_hash: "5ddb7c180fb38be67bd78a88a"
  docker_image_tag: "14.06"
  dockerfile_path: "dir/Dockerfile"
  repository: "MyDockerRepo"
  build_args:
  - "key=value"
  insecure_registry: true
  do_not_prune_images: true
  buildkit: true
  without_progress: true
  secret_id: "secretId"
  secret_src: "path_to_secret"
